import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import fg from "fast-glob";
import { transform } from "@svgr/core";

const rootDir = process.cwd();
const srcDir = path.join(rootDir, "src");
const componentsDir = path.join(rootDir, "src", "components");
const rootIndexFile = path.join(rootDir, "src", "index.ts");

function toPascalCase(value: string): string {
    return value
        .split(/[^a-zA-Z0-9]+/)
        .filter(Boolean)
        .map((part) => part[0].toUpperCase() + part.slice(1))
        .join("");
}

interface SvgEntry {
    /** Absolute path to the SVG file */
    absolutePath: string;
    /** Category folder name, e.g. "brand" */
    category: string;
    /** Original SVG filename without extension */
    baseName: string;
    /** PascalCase component name, e.g. "GithubIcon" */
    componentName: string;
}

async function discoverSvgs(): Promise<SvgEntry[]> {
    const pattern = path.join(srcDir, "**/*.svg").replace(/\\/g, "/");
    const files = await fg(pattern, {
        ignore: ["**/node_modules/**", "**/components/**", "**/scripts/**"],
        onlyFiles: true,
    });

    return files
        .map((file) => {
            const abs = path.resolve(file);
            const rel = path.relative(srcDir, abs);
            const parts = rel.split(path.sep);

            if (parts.length < 2) return null;

            const category = parts.slice(0, -1).join(path.sep);
            const baseName = path.basename(abs, ".svg");
            const componentName = `${toPascalCase(baseName)}Icon`;

            return {
                absolutePath: abs,
                category,
                baseName,
                componentName,
            } as SvgEntry;
        })
        .filter((entry): entry is SvgEntry => entry !== null)
        .sort((a, b) =>
            a.category === b.category
                ? a.componentName.localeCompare(b.componentName)
                : a.category.localeCompare(b.category),
        );
}

async function generateComponent(entry: SvgEntry): Promise<void> {
    const svgCode = await fs.readFile(entry.absolutePath, "utf8");

    const componentCode = await transform(
        svgCode,
        {
            typescript: true,
            memo: true,
            ref: true,
            dimensions: true,
            expandProps: "end",
            jsxRuntime: "automatic",
            exportType: "default",
            plugins: ["@svgr/plugin-svgo", "@svgr/plugin-jsx"],
            svgoConfig: {
                plugins: [
                    {
                        name: "preset-default",
                        params: { overrides: { removeViewBox: false } },
                    },
                ],
            },
        },
        { componentName: entry.componentName },
    );

    const relSvg = path
        .relative(srcDir, entry.absolutePath)
        .replace(/\\/g, "/");
    const output = `// Auto-generated from src/${relSvg}.\n${componentCode}\n`;

    const outDir = path.join(componentsDir, entry.category);
    await fs.mkdir(outDir, { recursive: true });

    const outFile = path.join(outDir, `${entry.componentName}.tsx`);
    await fs.writeFile(outFile, output, "utf8");
}

function groupByCategory(entries: SvgEntry[]): Map<string, SvgEntry[]> {
    const map = new Map<string, SvgEntry[]>();
    for (const entry of entries) {
        const list = map.get(entry.category) ?? [];
        list.push(entry);
        map.set(entry.category, list);
    }
    return map;
}

async function writeCategoryIndex(
    category: string,
    entries: SvgEntry[],
): Promise<void> {
    const lines = [
        "// This file is auto-generated by scripts/generate-icons.ts.",
        "",
    ];

    for (const entry of entries) {
        lines.push(
            `export { default as ${entry.componentName} } from "./${entry.componentName}";`,
        );
    }

    const indexPath = path.join(componentsDir, category, "index.ts");
    await fs.writeFile(indexPath, `${lines.join("\n")}\n`, "utf8");
}

async function writeRootIndex(grouped: Map<string, SvgEntry[]>): Promise<void> {
    const lines = [
        "// This file is auto-generated by scripts/generate-icons.ts.",
        "",
    ];

    const categories = [...grouped.keys()].sort();

    for (const category of categories) {
        const entries = grouped.get(category)!;
        for (const entry of entries) {
            const importPath = `./components/${category.replace(/\\/g, "/")}/${entry.componentName}`;
            lines.push(
                `export { default as ${entry.componentName} } from "${importPath}";`,
            );
        }
    }

    await fs.writeFile(rootIndexFile, `${lines.join("\n")}\n`, "utf8");
}

async function main(): Promise<void> {
    const entries = await discoverSvgs();

    if (entries.length === 0) {
        throw new Error(`No SVG files found under ${srcDir}`);
    }

    console.log(
        `Found ${entries.length} SVG(s) in ${new Set(entries.map((e) => e.category)).size} category(ies).`,
    );

    await fs.rm(componentsDir, { recursive: true, force: true });
    await fs.mkdir(componentsDir, { recursive: true });

    await Promise.all(entries.map(generateComponent));

    const grouped = groupByCategory(entries);

    for (const [category, catEntries] of grouped) {
        await writeCategoryIndex(category, catEntries);
    }

    await writeRootIndex(grouped);

    console.log("Icon generation complete.");
}

main().catch((error) => {
    console.error(error);
    process.exit(1);
});
